version: 2

group_defaults:
  approve_by_comment:
    approve_regex: '^:\+1:'
    enabled: true

groups:
  reviewers:
    required: 1
    conditions:
      branches:
        - master
    users:
      - als364
      - apchagi
      - danxmoran
      - gbggrant
      - hensonc
      - jacarey
      - ktibbett
      - nh13
      - pshapiro4broad
      - tbl3rd
      - tlangs
      - yfarjoun
